Journey_Project/Journey.WEB/Controllers/GoogleMapController.cs
using System.Collections.Generic;
using System.Web;
using System.Web.Mvc;
using Microsoft.Owin.Security;
using Microsoft.AspNet.Identity;
using Microsoft.AspNet.Identity.Owin;
using System.Threading.Tasks;
using Journey.WEB.Models;
using Journey.BLL.DTO;
using System.Security.Claims;
using Journey.BLL.Interfaces;
using Journey.BLL.Infrastructure;
using System.Net;


namespace Journey.WEB.Controllers
{
    public class GoogleMapController : Controller
    {

        private IUserService UserService
        {
            get
            {
                return HttpContext.GetOwinContext().GetUserManager<IUserService>();
            }
        }

        private IAuthenticationManager AuthenticationManager
        {
            get
            {
                return HttpContext.GetOwinContext().Authentication;
            }
        }
        // GET: GoogleMap
        public ActionResult SuccesCreated()
        {
            return View();
        }

        

        [Authorize]
        public ActionResult CreateRoute()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> CreateRoute(CreateRouteModel model)
        {
            if (ModelState.IsValid)
            {
                UserRouteDTO userRouteDto = new UserRouteDTO
                {
                    StartPoint = model.StartPoint,
                    Seats=model.Seats,
                    EndPoint = model.EndPoint,
                    Waypoints =string.Join(", ",model.Waypoints),
                    Date = model.Date,
                    UserID = User.Identity.GetUserId()
                };

                OperationDetails operationDetails = await UserService.CreateRoute(userRouteDto);
                if (operationDetails.Succedeed)
                    return View("SuccesCreated");
                else
                    ModelState.AddModelError(operationDetails.Property, operationDetails.Message);
            }

            return View();
        }
    }
}

Journey_Project/Journey.WEB/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Application name", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Home", "Index", "Home")</li>
                    <li>@Html.ActionLink("About", "About", "Home")</li>
                    <li>@Html.ActionLink("Contact", "Contact", "Home")</li>

                    <li>@Html.ActionLink("Создать маршрут", "CreateRoute", "GoogleMap")</li>
                    @if (User.IsInRole("admin"))
                    {
                        <li>@Html.ActionLink("Administration", "Administration", "Account")</li>
                    }
                </ul>
                <ul class="nav navbar-nav navbar-right">
                    @if (!User.Identity.IsAuthenticated)
                    {
                        <li>@Html.ActionLink("Войти", "Login", "Account")</li>
                        <li>@Html.ActionLink("Регистрация", "Register", "Account")</li>
                    }
                    else
                    {
                        <li>
                            @Html.ActionLink("Привет "+ @User.Identity.Name, "Profile", "Account")
                        </li>
                        <li>@Html.ActionLink("Выход", "Logout", "Account")</li>
                    }

                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
    </div>


    @RenderSection("scripts", required: false)
</body>
</html>